//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("LogicLibary", "OrderHeadOrderBodySet", "OrderHead", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.OrderHead), "OrderBodySet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.OrderBody))]
[assembly: EdmRelationshipAttribute("LogicLibary", "GoodsUnitGoods", "GoodsUnit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.GoodsUnit), "Goods", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.Goods))]
[assembly: EdmRelationshipAttribute("LogicLibary", "BrandGoods", "Brand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.Brand), "Goods", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.Goods))]
[assembly: EdmRelationshipAttribute("LogicLibary", "GoodsChanged", "Goods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.Goods), "ChangedSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.Changed))]
[assembly: EdmRelationshipAttribute("LogicLibary", "BrandBrand", "Brand", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.Brand), "ChildBrand", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LogicLibary.Brand))]
[assembly: EdmRelationshipAttribute("LogicLibary", "PriceGoods", "Price", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.Price), "Goods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.Goods))]
[assembly: EdmRelationshipAttribute("LogicLibary", "GoodsGoodsItem", "Goods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.Goods), "GoodsItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.GoodsItem))]
[assembly: EdmRelationshipAttribute("LogicLibary", "ChangedGoodsItem", "Changed", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LogicLibary.Changed), "GoodsItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LogicLibary.GoodsItem))]

#endregion

namespace LogicLibary
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StoreEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StoreEntities”部分中的连接字符串初始化新 StoreEntities 对象。
        /// </summary>
        public StoreEntities() : base("name=StoreEntities", "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StoreEntities 对象。
        /// </summary>
        public StoreEntities(string connectionString) : base(connectionString, "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StoreEntities 对象。
        /// </summary>
        public StoreEntities(EntityConnection connection) : base(connection, "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OrderBody> OrderBodySet
        {
            get
            {
                if ((_OrderBodySet == null))
                {
                    _OrderBodySet = base.CreateObjectSet<OrderBody>("OrderBodySet");
                }
                return _OrderBodySet;
            }
        }
        private ObjectSet<OrderBody> _OrderBodySet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OrderHead> OrderHeadSet
        {
            get
            {
                if ((_OrderHeadSet == null))
                {
                    _OrderHeadSet = base.CreateObjectSet<OrderHead>("OrderHeadSet");
                }
                return _OrderHeadSet;
            }
        }
        private ObjectSet<OrderHead> _OrderHeadSet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Entity> EntitySet
        {
            get
            {
                if ((_EntitySet == null))
                {
                    _EntitySet = base.CreateObjectSet<Entity>("EntitySet");
                }
                return _EntitySet;
            }
        }
        private ObjectSet<Entity> _EntitySet;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 OrderBodySet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrderBodySet(OrderBody orderBody)
        {
            base.AddObject("OrderBodySet", orderBody);
        }
    
        /// <summary>
        /// 用于向 OrderHeadSet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrderHeadSet(OrderHead orderHead)
        {
            base.AddObject("OrderHeadSet", orderHead);
        }
    
        /// <summary>
        /// 用于向 EntitySet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToEntitySet(Entity entity)
        {
            base.AddObject("EntitySet", entity);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Brand : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Brand 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="brandName">BrandName 属性的初始值。</param>
        public static Brand CreateBrand(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.String brandName)
        {
            Brand brand = new Brand();
            brand.ID = id;
            brand.UserKey = userKey;
            brand.Modified = modified;
            brand.BrandName = brandName;
            return brand;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BrandName
        {
            get
            {
                return _BrandName;
            }
            set
            {
                OnBrandNameChanging(value);
                ReportPropertyChanging("BrandName");
                _BrandName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BrandName");
                OnBrandNameChanged();
            }
        }
        private global::System.String _BrandName;
        partial void OnBrandNameChanging(global::System.String value);
        partial void OnBrandNameChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "BrandGoods", "Goods")]
        public EntityCollection<Goods> Goods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Goods>("LogicLibary.BrandGoods", "Goods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Goods>("LogicLibary.BrandGoods", "Goods", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "BrandBrand", "ChildBrand")]
        public Brand RootBrand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandBrand", "ChildBrand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandBrand", "ChildBrand").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Brand> RootBrandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandBrand", "ChildBrand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Brand>("LogicLibary.BrandBrand", "ChildBrand", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "BrandBrand", "Brand")]
        public EntityCollection<Brand> ChildBrandSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Brand>("LogicLibary.BrandBrand", "Brand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Brand>("LogicLibary.BrandBrand", "Brand", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="Changed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Changed : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Changed 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        /// <param name="date">Date 属性的初始值。</param>
        /// <param name="quantity">Quantity 属性的初始值。</param>
        /// <param name="pieceCost">PieceCost 属性的初始值。</param>
        /// <param name="sumCost">SumCost 属性的初始值。</param>
        /// <param name="source">Source 属性的初始值。</param>
        public static Changed CreateChanged(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.Decimal value, global::System.DateTime date, global::System.Decimal quantity, global::System.Decimal pieceCost, global::System.Decimal sumCost, global::System.String source)
        {
            Changed changed = new Changed();
            changed.ID = id;
            changed.UserKey = userKey;
            changed.Modified = modified;
            changed.Value = value;
            changed.Date = date;
            changed.Quantity = quantity;
            changed.PieceCost = pieceCost;
            changed.SumCost = sumCost;
            changed.Source = source;
            return changed;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PieceCost
        {
            get
            {
                return _PieceCost;
            }
            set
            {
                OnPieceCostChanging(value);
                ReportPropertyChanging("PieceCost");
                _PieceCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PieceCost");
                OnPieceCostChanged();
            }
        }
        private global::System.Decimal _PieceCost;
        partial void OnPieceCostChanging(global::System.Decimal value);
        partial void OnPieceCostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SumCost
        {
            get
            {
                return _SumCost;
            }
            set
            {
                OnSumCostChanging(value);
                ReportPropertyChanging("SumCost");
                _SumCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SumCost");
                OnSumCostChanged();
            }
        }
        private global::System.Decimal _SumCost;
        partial void OnSumCostChanging(global::System.Decimal value);
        partial void OnSumCostChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsChanged", "Goods")]
        public Goods Goods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsChanged", "Goods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsChanged", "Goods").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Goods> GoodsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsChanged", "Goods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Goods>("LogicLibary.GoodsChanged", "Goods", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "ChangedGoodsItem", "GoodsItem")]
        public EntityCollection<GoodsItem> GoodsItemSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GoodsItem>("LogicLibary.ChangedGoodsItem", "GoodsItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GoodsItem>("LogicLibary.ChangedGoodsItem", "GoodsItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="Entity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(GoodsUnit))]
    [KnownTypeAttribute(typeof(Goods))]
    [KnownTypeAttribute(typeof(Brand))]
    [KnownTypeAttribute(typeof(Changed))]
    [KnownTypeAttribute(typeof(Price))]
    [KnownTypeAttribute(typeof(GoodsItem))]
    public abstract partial class Entity : EntityObject
    {
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserKey
        {
            get
            {
                return _UserKey;
            }
            set
            {
                OnUserKeyChanging(value);
                ReportPropertyChanging("UserKey");
                _UserKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserKey");
                OnUserKeyChanged();
            }
        }
        private global::System.String _UserKey;
        partial void OnUserKeyChanging(global::System.String value);
        partial void OnUserKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="Goods")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Goods : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Goods 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="goodsName">GoodsName 属性的初始值。</param>
        /// <param name="quantity">Quantity 属性的初始值。</param>
        public static Goods CreateGoods(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.String goodsName, global::System.Decimal quantity)
        {
            Goods goods = new Goods();
            goods.ID = id;
            goods.UserKey = userKey;
            goods.Modified = modified;
            goods.GoodsName = goodsName;
            goods.Quantity = quantity;
            return goods;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GoodsName
        {
            get
            {
                return _GoodsName;
            }
            set
            {
                OnGoodsNameChanging(value);
                ReportPropertyChanging("GoodsName");
                _GoodsName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GoodsName");
                OnGoodsNameChanged();
            }
        }
        private global::System.String _GoodsName;
        partial void OnGoodsNameChanging(global::System.String value);
        partial void OnGoodsNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private global::System.Boolean _Enable = false;
        partial void OnEnableChanging(global::System.Boolean value);
        partial void OnEnableChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsUnitGoods", "GoodsUnit")]
        public GoodsUnit Unit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GoodsUnit>("LogicLibary.GoodsUnitGoods", "GoodsUnit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GoodsUnit>("LogicLibary.GoodsUnitGoods", "GoodsUnit").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GoodsUnit> UnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GoodsUnit>("LogicLibary.GoodsUnitGoods", "GoodsUnit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GoodsUnit>("LogicLibary.GoodsUnitGoods", "GoodsUnit", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "BrandGoods", "Brand")]
        public Brand Brand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandGoods", "Brand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandGoods", "Brand").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Brand> BrandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Brand>("LogicLibary.BrandGoods", "Brand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Brand>("LogicLibary.BrandGoods", "Brand", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsChanged", "ChangedSet")]
        public EntityCollection<Changed> ChangedSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Changed>("LogicLibary.GoodsChanged", "ChangedSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Changed>("LogicLibary.GoodsChanged", "ChangedSet", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "PriceGoods", "Price")]
        public EntityCollection<Price> PriceSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Price>("LogicLibary.PriceGoods", "Price");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Price>("LogicLibary.PriceGoods", "Price", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsGoodsItem", "GoodsItem")]
        public EntityCollection<GoodsItem> GoodsItemSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GoodsItem>("LogicLibary.GoodsGoodsItem", "GoodsItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GoodsItem>("LogicLibary.GoodsGoodsItem", "GoodsItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="GoodsItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GoodsItem : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GoodsItem 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="itemIdenifity">ItemIdenifity 属性的初始值。</param>
        /// <param name="productionDate">ProductionDate 属性的初始值。</param>
        /// <param name="expiryDate">ExpiryDate 属性的初始值。</param>
        /// <param name="quantity">Quantity 属性的初始值。</param>
        public static GoodsItem CreateGoodsItem(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.String itemIdenifity, global::System.String productionDate, global::System.String expiryDate, global::System.Decimal quantity)
        {
            GoodsItem goodsItem = new GoodsItem();
            goodsItem.ID = id;
            goodsItem.UserKey = userKey;
            goodsItem.Modified = modified;
            goodsItem.ItemIdenifity = itemIdenifity;
            goodsItem.ProductionDate = productionDate;
            goodsItem.ExpiryDate = expiryDate;
            goodsItem.Quantity = quantity;
            return goodsItem;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemIdenifity
        {
            get
            {
                return _ItemIdenifity;
            }
            set
            {
                OnItemIdenifityChanging(value);
                ReportPropertyChanging("ItemIdenifity");
                _ItemIdenifity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemIdenifity");
                OnItemIdenifityChanged();
            }
        }
        private global::System.String _ItemIdenifity;
        partial void OnItemIdenifityChanging(global::System.String value);
        partial void OnItemIdenifityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductionDate
        {
            get
            {
                return _ProductionDate;
            }
            set
            {
                OnProductionDateChanging(value);
                ReportPropertyChanging("ProductionDate");
                _ProductionDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductionDate");
                OnProductionDateChanged();
            }
        }
        private global::System.String _ProductionDate;
        partial void OnProductionDateChanging(global::System.String value);
        partial void OnProductionDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExpiryDate
        {
            get
            {
                return _ExpiryDate;
            }
            set
            {
                OnExpiryDateChanging(value);
                ReportPropertyChanging("ExpiryDate");
                _ExpiryDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExpiryDate");
                OnExpiryDateChanged();
            }
        }
        private global::System.String _ExpiryDate;
        partial void OnExpiryDateChanging(global::System.String value);
        partial void OnExpiryDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsGoodsItem", "Goods")]
        public Goods Goods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsGoodsItem", "Goods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsGoodsItem", "Goods").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Goods> GoodsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.GoodsGoodsItem", "Goods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Goods>("LogicLibary.GoodsGoodsItem", "Goods", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "ChangedGoodsItem", "Changed")]
        public Changed Changed
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Changed>("LogicLibary.ChangedGoodsItem", "Changed").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Changed>("LogicLibary.ChangedGoodsItem", "Changed").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Changed> ChangedReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Changed>("LogicLibary.ChangedGoodsItem", "Changed");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Changed>("LogicLibary.ChangedGoodsItem", "Changed", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="GoodsUnit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GoodsUnit : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GoodsUnit 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="unitName">UnitName 属性的初始值。</param>
        public static GoodsUnit CreateGoodsUnit(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.String unitName)
        {
            GoodsUnit goodsUnit = new GoodsUnit();
            goodsUnit.ID = id;
            goodsUnit.UserKey = userKey;
            goodsUnit.Modified = modified;
            goodsUnit.UnitName = unitName;
            return goodsUnit;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                OnUnitNameChanging(value);
                ReportPropertyChanging("UnitName");
                _UnitName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UnitName");
                OnUnitNameChanged();
            }
        }
        private global::System.String _UnitName;
        partial void OnUnitNameChanging(global::System.String value);
        partial void OnUnitNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private global::System.Boolean _Enable = false;
        partial void OnEnableChanging(global::System.Boolean value);
        partial void OnEnableChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "GoodsUnitGoods", "Goods")]
        public EntityCollection<Goods> GoodsSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Goods>("LogicLibary.GoodsUnitGoods", "Goods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Goods>("LogicLibary.GoodsUnitGoods", "Goods", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="OrderBody")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderBody : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OrderBody 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        public static OrderBody CreateOrderBody(global::System.Int32 id, global::System.Int16 value)
        {
            OrderBody orderBody = new OrderBody();
            orderBody.ID = id;
            orderBody.Value = value;
            return orderBody;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int16 _Value;
        partial void OnValueChanging(global::System.Int16 value);
        partial void OnValueChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "OrderHeadOrderBodySet", "OrderHead")]
        public OrderHead OrderHead
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderHead>("LogicLibary.OrderHeadOrderBodySet", "OrderHead").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderHead>("LogicLibary.OrderHeadOrderBodySet", "OrderHead").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderHead> OrderHeadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderHead>("LogicLibary.OrderHeadOrderBodySet", "OrderHead");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderHead>("LogicLibary.OrderHeadOrderBodySet", "OrderHead", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="OrderHead")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderHead : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OrderHead 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="buyer">Buyer 属性的初始值。</param>
        /// <param name="sum">Sum 属性的初始值。</param>
        public static OrderHead CreateOrderHead(global::System.Int32 id, global::System.String buyer, global::System.Int32 sum)
        {
            OrderHead orderHead = new OrderHead();
            orderHead.ID = id;
            orderHead.Buyer = buyer;
            orderHead.Sum = sum;
            return orderHead;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Buyer
        {
            get
            {
                return _Buyer;
            }
            set
            {
                OnBuyerChanging(value);
                ReportPropertyChanging("Buyer");
                _Buyer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Buyer");
                OnBuyerChanged();
            }
        }
        private global::System.String _Buyer;
        partial void OnBuyerChanging(global::System.String value);
        partial void OnBuyerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                OnSumChanging(value);
                ReportPropertyChanging("Sum");
                _Sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sum");
                OnSumChanged();
            }
        }
        private global::System.Int32 _Sum;
        partial void OnSumChanging(global::System.Int32 value);
        partial void OnSumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status = "NEW";
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "OrderHeadOrderBodySet", "OrderBodySet")]
        public EntityCollection<OrderBody> OrderBodySet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderBody>("LogicLibary.OrderHeadOrderBodySet", "OrderBodySet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderBody>("LogicLibary.OrderHeadOrderBodySet", "OrderBodySet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogicLibary", Name="Price")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Price : Entity
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Price 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userKey">UserKey 属性的初始值。</param>
        /// <param name="modified">Modified 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        /// <param name="beforeTax">BeforeTax 属性的初始值。</param>
        /// <param name="discountLimits">DiscountLimits 属性的初始值。</param>
        public static Price CreatePrice(global::System.Int32 id, global::System.String userKey, global::System.DateTime modified, global::System.Decimal value, global::System.Boolean beforeTax, global::System.Decimal discountLimits)
        {
            Price price = new Price();
            price.ID = id;
            price.UserKey = userKey;
            price.Modified = modified;
            price.Value = value;
            price.BeforeTax = beforeTax;
            price.DiscountLimits = discountLimits;
            return price;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BeforeTax
        {
            get
            {
                return _BeforeTax;
            }
            set
            {
                OnBeforeTaxChanging(value);
                ReportPropertyChanging("BeforeTax");
                _BeforeTax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeforeTax");
                OnBeforeTaxChanged();
            }
        }
        private global::System.Boolean _BeforeTax;
        partial void OnBeforeTaxChanging(global::System.Boolean value);
        partial void OnBeforeTaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DiscountLimits
        {
            get
            {
                return _DiscountLimits;
            }
            set
            {
                OnDiscountLimitsChanging(value);
                ReportPropertyChanging("DiscountLimits");
                _DiscountLimits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountLimits");
                OnDiscountLimitsChanged();
            }
        }
        private global::System.Decimal _DiscountLimits;
        partial void OnDiscountLimitsChanging(global::System.Decimal value);
        partial void OnDiscountLimitsChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogicLibary", "PriceGoods", "Goods")]
        public Goods Goods
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.PriceGoods", "Goods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.PriceGoods", "Goods").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Goods> GoodsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Goods>("LogicLibary.PriceGoods", "Goods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Goods>("LogicLibary.PriceGoods", "Goods", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
